spring:
  application:
    name: config-server
#  profiles:
#    active: composite
#  cloud:
#    config:
#      server:
#        composite:
#          - type: git
#            uri: https://github.com/AndreyRamanovsky/extension-properties
#            search-paths: shared, shared/environments, services/platforms/core/{application}
#            default-label: main
#          - type: git
#            uri: https://github.com/AndreyRamanovsky/core-properties # Base config should be the last
#            search-paths: shared, shared/environments, services/platforms/core/{application}
#            default-label: main
#        bootstrap: false
#      enabled: true

server:
  port: 8888

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.config.server: DEBUG
    org.eclipse.jgit: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always